GET http://localhost:3003/players/

###
GET http://localhost:3003/players/2/

###
PUT http://localhost:3003/players/4/
Content-Type: application/json

{
    "playerName": "Raju"
}

###

GET http://localhost:3003/matches/18/

###

GET http://localhost:3003/players/2/matches

###

GET http://localhost:3003/matches/2/players/

###

GET http://localhost:3003/players/1/playerScores/

###